name: Update TLDs

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at midnight on the first day of every month

jobs:
  update-tlds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm install

      - name: Update TLDs
        run: npm run update-tlds

      - name: Commit and push updated TLDs
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add dist/tlds.json
          git commit -m "Update TLDs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
