name: Update TLDs

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tlds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Update TLDs
        run: npm run update-tlds

      - name: Configure Git
        run: |
          git config --global user.email "branislavjaksic3@gmail.com"
          git config --global user.name "Branislav Jaksic"

      - name: Commit and push updated TLDs
        run: |
          if [ -f src/tlds.json ]; then
            git add src/tlds.json
            git commit -m "Update TLDs" || echo "No changes to commit"
            git push
          else
            echo "File src/tlds.json does not exist."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
